### ISSUE TITLE
Compilation Issue on rust 1.41.0

### ISSUE THREAD

**Issue by dbcfd** [BurntSushi/rust-memchr#68]
```rust
error[E0428]: the name `imp` is defined multiple times
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/memchr-2.3.1/src/lib.rs:148:5
    |
139 |     fn imp(n1: u8, haystack: &[u8]) -> Option<usize> {
    |     ------------------------------------------------ previous definition of the value `imp` here
...
148 |     fn imp(n1: u8, haystack: &[u8]) -> Option<usize> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `imp` redefined here
    |
    = note: `imp` must be defined only once in the value namespace of this block
```

**Comment by dbcfd** [comment]
System info 

```
info: using existing install for 'stable-x86_64-apple-darwin'
info: default toolchain set to 'stable-x86_64-apple-darwin'

  stable-x86_64-apple-darwin unchanged - rustc 1.41.0 (5e1a79984 2020-01-27)
```

**Comment by dbcfd** [comment]
This also happens on beta and nightly.

**Comment by BurntSushi** [comment]
I'ved yanked `2.3.1` from crates.io until I have time to properly investigate this. cc @ldesgoui 

(It was almost certainly caused by #67.)

**Comment by BurntSushi** [comment]
I'm particular, I would like to know why CI didn't catch this.

**Comment by CryZe** [comment]
https://github.com/BurntSushi/rust-memchr/pull/67/files#diff-b4aea3e418ccdb71239b96952d9cddb6R145

This should be not(miri)

**Comment by ldesgoui** [comment]
My bad! I'll be home in 10 to fix, not(all(a, b, c)) should be all(not(all(a, b)), not(c))

**Comment by BurntSushi** [comment]
No rush. It is yanked so there should be anyone impacted by this now. But yeah, thank you. I also need to figure out how to make sure this case is tested in CI.

**Comment by kali** [comment]
If it can help, I see it from a github action CI here  https://github.com/snipsco/tract/runs/441345982?check_suite_focus=true

**Comment by ldesgoui** [comment]
The compilation error is caused by the logic detecting when the C should be used, which is `memchr_libc AND (NOT (x86_64 AND memchr_runtime_simd)) AND (NOT miri)` which translates to
`cfg(all( memchr_libc, not(all(target_arch = "x86_64", memchr_runtime_simd)), not(miri) )`
Here's the truth table comparing what we have/what we want:

| x64 | simd | miri | !(x64 && simd && miri) | !(x64 && simd) && !miri |       |
|-----|------|------|------------------------|-------------------------|-------|
| f   | f    | f    | t                      | t                       |       |
| f   | f    | t    | t                      | f                       | wrong |
| f   | t    | f    | t                      | t                       |       |
| f   | t    | t    | t                      | f                       | wrong |
| t   | f    | f    | t                      | t                       |       |
| t   | f    | t    | t                      | f                       | wrong |
| t   | t    | f    | t                      | f                       | wrong |
| t   | t    | t    | f                      | f                       |       |

4 wrong cases, the one hit by users was most likely x64 = t, simd = t, miri = f

**Comment by ldesgoui** [comment]
This case is not tested in there:
https://github.com/BurntSushi/rust-memchr/blob/2.3.1/.github/workflows/ci.yml#L100-L122
Incoming PR with fix and according CI test
