### PR TITLE
Fix compilation error introduced in #67, increase test coverage against this issue

### LINKED ISSUE #68: Compilation Issue on rust 1.41.0
```rust
error[E0428]: the name `imp` is defined multiple times
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/memchr-2.3.1/src/lib.rs:148:5
    |
139 |     fn imp(n1: u8, haystack: &[u8]) -> Option<usize> {
    |     ------------------------------------------------ previous definition of the value `imp` here
...
148 |     fn imp(n1: u8, haystack: &[u8]) -> Option<usize> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `imp` redefined here
    |
    = note: `imp` must be defined only once in the value namespace of this block
```

### PR DESCRIPTION
**Pull request by ldesgoui**
Closes #68 
Apologies once again for the inconveniences

### CODE REVIEW

File: src/tests/miri.rs [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+    assert_eq!(memchr2(b'z', b'y', b"abcda"), None);
+    assert_eq!(memchr3(b'a', b'z', b'b', b"abcda"), Some(0));
+    assert_eq!(memchr3(b'z', b'y', b'x', b"abcda"), None);
+    assert_eq!(memrchr(b'a', b"abcda"), Some(4));
+    assert_eq!(memrchr(b'z', b"abcda"), None);
+    assert_eq!(memrchr2(b'a', b'z', b"abcda"), Some(4));
+    assert_eq!(memrchr2(b'z', b'y', b"abcda"), None);
+    assert_eq!(memrchr3(b'a', b'z', b'b', b"abcda"), Some(4));
+    assert_eq!(memrchr3(b'z', b'y', b'x', b"abcda"), None);
+}
```
Comment (BurntSushi) [inline src/tests/miri.rs]: Out of curiosity, why are these needed? Why can't miri just use the normal test suite?

(Sorry if this is a stupid question, I haven't actually used miri yet!)

**Comment by BurntSushi** [comment]
All righty, let's try this again! :) This PR is on crates.io in `memchr 2.3.2`.

File: src/tests/miri.rs (hunk 1 above)
Comment (ldesgoui) [reply src/tests/miri.rs]: MIRI is magnitudes slower (100x, maybe even 1000x/10000x) than binaries built in debug mode
I tried running the test suite, the first test would show up as complete relatively quickly but no other test would complete for another few minutes
I assume there are timeout limits on GitHub actions, hence the short test, I suppose that the existing test suite could work just fine, I didn't really have the time to stick around :)

Comment (BurntSushi) [reply src/tests/miri.rs]: Ah gotya. Yeah the tests check all the possible different offsets and alignments. This gets quite big because of the 256 bit vectors in the AVX version. It's probably possible to merge the test suites and just run fewer iterations when miri is enabled. I'll look into that when I get a chance!
